version: '3.8'

services:
  postgres:
    container_name: school_management_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - 'db_school_management:/var/lib/postgresql/data'

volumes:
  db_school_management: