version: '3.8'

services:
  postgres:
    container_name: school_management_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=school_management
    volumes:
      - 'db_school_management:/var/lib/postgresql/data'

volumes:
  db_school_management: