# Generated by Django 5.0.4 on 2024-05-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
