# Generated by Django 5.0.4 on 2024-07-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_active_alter_student_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cellphone',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
    ]
